export const ROUTE_RESOURCE = {
  dashboard: 'dashboard',
  calendar: 'calendar',
  orders: 'orders',
  suppliers: 'suppliers',
  chats: 'chats',
  finance: 'finance',
  documents: 'documents',
  receipts: 'documents',
  fulfillment: 'documents',
  settings: 'users',
  clients: 'clients',
  companies: 'companies',
  offers: 'proposals',
  notifications: 'notifications',
  returns: 'returns',
  services: 'orderServices',
  flights: 'orderServices',
  rail: 'orderServices',
  hotels: 'orderServices',
  transfers: 'orderServices',
  buses: 'orderServices',
  tours: 'orderServices',
};

